### ISSUE TITLE
Initial connection failed with ConnectionError: could not establish signal connection: room connection has timed out (signal)

### ISSUE THREAD

**Issue by IIvexII** [livekit/client-sdk-react-native#215]
**Describe the bug**

It was working fine but suddenly getting this connection error, although the url is accessable and does not seem like a url issue. I have some previous apks from previous build and they are perfectly fine but when i am creating new one they are logging this message of connection time out. I have not changed any version of package in the package,json file

**Screenshot**

![Image](https://github.com/user-attachments/assets/fd0e681a-cd1d-4d11-8967-c6751af65728)

**Device Info:**

 - OS: Windows 

**Dependencies Info (please reference your package-lock.json or yarn.lock file, not just your package.json):**

- "@livekit/react-native": "^2.6.4",
- "@livekit/react-native-expo-plugin": "^1.0.1",
- "@livekit/react-native-webrtc": "^125.0.9",
-  "expo": "~52.0.11",
- "react-native": "0.76.3",

**Comment by IIvexII** [comment]
@davidliu I have created a minimal repo for you to test out, this is showing the same error to me:

https://github.com/IIvexII/MinimalRepoForLivekitIssue

**Comment by IIvexII** [comment]
I have resolved the issue by downgrading the livekit-client version from 2.9.7 to 2.9.3.

**Comment by davidliu** [comment]
Will be fixed in next livekit-client release, PR is here: https://github.com/livekit/client-sdk-js/pull/1443

**Comment by davidliu** [comment]
Fixed in `livekit-client@2.9.8`

**Comment by harshit-dignizant** [comment]
@davidliu @IIvexII hi, I have tried this but I'm still facing the same issue. 

"@livekit/react-native": "^2.6.5",
"@livekit/react-native-webrtc": "^125.0.9",
"livekit-client": "^2.9.8",

please check these versions.

**Comment by harshit-dignizant** [comment]
@IIvexII 

As per your suggestion, I have removed the ^ from these libraries and deleted yarn, pods, yarn.lock, and Podfile.lock. After that, I reinstalled everything, killed Metro, and restarted it with a cleared cache. However, I am still facing the same issue.

**Comment by davidliu** [comment]
@harshit-dignizant can you provide your logs?

**Comment by harshit-dignizant** [comment]
@davidliu

(NOBRIDGE) WARN  websocket closed {"code": 1006, "pID": undefined, "participant": undefined, "reason": "The operation couldn’t be completed. (OSStatus error -9847.)", "room": undefined, "roomID": undefined, "state": 4, "wasClean": undefined}

 (NOBRIDGE) WARN  Couldn't connect to server, attempt 1 of 1 {"pID": undefined, "participant": undefined, "room": undefined, "roomID": undefined}

 (NOBRIDGE) LOG  error ===>  [ConnectionError: could not establish signal connection: Network request failed]

**Comment by davidliu** [comment]
https://www.osstatus.com/search/results?platform=all&framework=all&search=-9847

Looks like you're trying to connect to an unsecure server with the `wss://` protocol (e.g. your own private server). Use `ws://` instead for your URL (though you'll also have to allow abitrary loads for your app to do so, and should not be used in production).

**Comment by harshit-dignizant** [comment]
@davidliu My code was working fine until last Thursday, but when I resumed work on Monday, it started throwing this error despite no changes on my end. Nevertheless, I'll review the changes you suggested.

**Comment by IIvexII** [comment]
> [@davidliu](https://github.com/davidliu)
> 
> (NOBRIDGE) WARN websocket closed {"code": 1006, "pID": undefined, "participant": undefined, "reason": "The operation couldn’t be completed. (OSStatus error -9847.)", "room": undefined, "roomID": undefined, "state": 4, "wasClean": undefined}
> 
> (NOBRIDGE) WARN Couldn't connect to server, attempt 1 of 1 {"pID": undefined, "participant": undefined, "room": undefined, "roomID": undefined}
> 
> (NOBRIDGE) LOG error ===> [ConnectionError: could not establish signal connection: Network request failed]

It seems like the issue is on the backend, can you verify the server url is accessible.

**Comment by harshit-dignizant** [comment]
@IIvexII I'm encountering this issue only in React Native, while the same URL works fine in React.js. So, it may not be a backend issue. However, I'll still verify it.

**Comment by harshit-dignizant** [comment]
@davidliu @IIvexII I've thoroughly checked everything, and it all looks fine. I’ve also tested it on localhost, and it works perfectly for React.js, but not for React Native.

If you have any suggestions or ideas, please let me know.

**thanks**

**Comment by harshit-dignizant** [comment]
> I have resolved the issue by downgrading the livekit-client version from 2.9.7 to 2.9.3.

I encountered the same issue as @IIvexII after installing from Stash. To resolve it, I updated the livekit-client library to version 2.9.3, and everything started working fine.

Here are the updated library versions:

    "@livekit/react-native": "^2.6.5",
    "@livekit/react-native-webrtc": "^125.0.9",
    "livekit-client": "2.9.3",

Thanks

**Comment by davidliu** [comment]
Are you sure you were on `livekit-client` 2.9.8 in the first place? Check your yarn.lock/package-lock file.
